// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { PriceConverter$Type } from "./PriceConverter";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["PriceConverter"]: PriceConverter$Type;
    ["contracts/PriceConverter.sol:PriceConverter"]: PriceConverter$Type;
  }
}
